### PR TITLE
Dev mike

### LINKED ISSUE #3: Styling the platform
Personally, I'm not keen on the very flat, low-contrast styling of the default Backpack page. I think it needs some more contrast between the sidebar, header / menu bar and the main body. 

Fortunately, in `config/backpack/base.php`, you have a bunch of config options that can quickly change the overall look. 

Have a look at https://backpackforlaravel.com/docs/4.0/base-how-to#customizing-the-design-of-the-menu-sidebar-footer. 

You can go incredibly deep and add your own custom css, or even overwrite any of the backpack blade files entirely, but I suggest just seeing what you can do by updating the classes in the base config file.

### LINKED ISSUE #4: Display uploaded files in List / Show views
Given we've messed around with how the file metadata is stored in the database, we need to customise the column for display. 

We should [create a custom column](https://backpackforlaravel.com/docs/4.0/crud-columns#creating-a-custom-column-type) to display the uploaded files, as the default "upload_multiple" doesn't work. 

I suggest you start with the code from `upload_multiple.blade.php` and modify it. I'd like the files displayed in the list table roughly like this: 

 - File1 Original Upload Name.ext (2.5MB)
 - File2 Original Upload Name.ext (890KB)
 - File3 Original Upload Name.ext (25.2MB)

Clicking on each file name would download it. You'll need to unpack the $value you get and figure out how to get each part of the file metadata.

### LINKED ISSUE #5: Add 'admin' role, and allow only admins to access user information
A non-admin should not be able to load the User, Role or Permission crud panel at all as a basic security feature.

### LINKED ISSUE #6: Validation rules for Resources / Types.
When I try to add a resource without a title, I get the following error: 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (SQL: insert into `resources` (`title`, `description`, `uploads`, `uploaded_by`, `updated_at`, `created_at`) values (?, ?, ["uploads"], 1, 2020-03-08 16:48:58, 2020-03-08 16:48:58))
```

Screenshot 2020-03-08 at 16 49 58

I get a similar error when adding a type without a label. Some validation rules would help here!

### PR DESCRIPTION
**Pull request by mikensubuga**
Changes for the following issues:
- Closes #3 
- Closes #4 
- Closes #5 
- Closes #6

### CODE REVIEW

File: app/Helpers/CustomHelper.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            $bytes = $bytes . ' bytes';
+        }
+        elseif ($bytes == 1)
+        {
+            $bytes = $bytes . ' byte';
+        }
+        else
+        {
+            $bytes = '0 bytes';
+        }
```
Comment (dave-mills) [inline app/Helpers/CustomHelper.php:33]: Nothing needed here - this function works well and I like the attention to detail shown distinguishing between singular and plural in the case where a file is 1 single byte! 

That said - a few comments.

**A note on refactoring**
I recently watched a [video on declarative vs imperative coding](https://laracasts.com/series/guest-spotlight/episodes/4). The presenter discussed "lookup tables" in code - a practice of separating your code into "things that change" and "things that happen". 

Your function here is perfectly good - it works fine, is understandable and is almost exactly what I wrote on my first pass at this function. But it's not hugely elegant. A long set of `elseif`s like this is a good indicator that this function could be refactored at some point. 

**My version**
My version (below, from the GenericHelper class) is also not perfect - as you noted, it's not easy to understand what's happening - why is the `for` loop there? What's happening to the $bytes variable? But it does do a couple of things:

 - it puts all the strings (the things that change) together in one place. So if we ever wanted to change it, e.g. to use the longform "bytes, kilobytes etc", it's easy to do. 
 - it has only a single path through the code,  so it's (potentially) easier to debug if something goes wrong. 






```
public static function fileSizeToHuman($bytes)
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB' ,'PB'];

        for($i = 0; $bytes > 1024; $i++){
            $bytes /= 1024;
        }

        return round($bytes, 2) . ' ' . $units[$i];
    }
```

**Review by dave-mills — APPROVED** [review]
Looks good!
